services:
  # Next.js Application Service
  ahmadcodes_nextjs:
    build:
      context: ./frontend
      target: production
    # image: ahmadcodes_nextjs:1.0.0
    container_name: ahmadcodes_nextjs
    networks:
      - ahmadCodes_intranet
    restart: always
    env_file: .env.local
    depends_on:
      - blog_nestjs
    labels:
      - 'service=app'
      - 'stage=production'
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"http\").get(\"http://localhost:3000/\", (res) => { if (res.statusCode === 200) process.exit(0); else process.exit(1); })'"]
      interval: 30s
      timeout: 10s
      retries: 3

  # NestJS API Service
  blog_nestjs:
    build:
      context: ./backend
      target: production
    image: blog_nestjs:1.0.0
    container_name: nestjs_blog
    networks:
      - ahmadCodes_intranet
    volumes:
      - ./uploads:/uploads
    restart: always
    env_file: .env.local
    command: node dist/main.js
    stdin_open: true
    tty: true

  # Nginx Reverse Proxy Service
  nginx:
    image: nginx:1.25.0
    container_name: nginx_reverse_proxy
    networks:
      - ahmadCodes_intranet
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - ahmadcodes_nextjs
      - blog_nestjs
    restart: always

networks:
  ahmadCodes_intranet:
    name: ahmadCodes_intranet
    driver: bridge
